services:
  stats-server:
    container_name: stats-server
    build: ./ewm-stats-service/stats-service-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=adminpassword
    restart: on-failure

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  db-data:
  server-logs:

#  main-server:
#    container_name: main-server
#    build: ./ewm-main-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - main-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm-main
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=adminpassword
#    restart: on-failure
#
#  main-db:
#    image: postgres:13.7-alpine
#    container_name: main-db
#    ports:
#      - "6542:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=ewm-main
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=adminpassword
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U admin" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    restart: on-failure
