DROP TABLE IF EXISTS hit CASCADE;

CREATE TABLE IF NOT EXISTS hit (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app           VARCHAR(255)                            NOT NULL,
  uri           VARCHAR(255)                            NOT NULL,
  ip            VARCHAR(255)                            NOT NULL,
  hit_timestamp TIMESTAMP without time zone             NOT NULL,
  constraint pk_hit PRIMARY KEY (id)
);
